# Generated by Django 3.0.2 on 2020-05-08 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emailupdates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailupdate',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailupdate',
            name='update_field',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
