# Generated by Django 2.2 on 2020-07-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailupdates', '0003_auto_20200510_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailupdate',
            old_name='update_field',
            new_name='Email',
        ),
    ]
