# Generated by Django 3.0.8 on 2020-09-08 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20200908_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Messages'},
        ),
    ]
