# Generated by Django 3.0.8 on 2020-10-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Sarees', 'Sarees'), ('Nighties', 'Nighties'), ('Dress materials', 'Dress materials'), ('Tops', 'Tops')], max_length=50),
        ),
    ]
